# Generated by Django 5.0.7 on 2024-08-06 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='condominio_tabela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_condominio', models.TextField()),
                ('regras_mudanca', models.TextField()),
                ('diretorio', models.TextField()),
            ],
        ),
    ]
