# Generated by Django 5.0.7 on 2024-07-31 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CondominioDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_condominio', models.TextField()),
                ('regras_mudanca', models.TextField()),
                ('diretorio', models.TextField()),
            ],
            options={
                'db_table': 'condominioDB',
            },
        ),
    ]
